"use client";
import { useActionState, useEffect, useRef } from "react";
import Image from "next/image";
import { useToast } from "@/components/ui/toast";
import type { ActionResult } from "@/lib/action-result";
import { updateMosqueProfileAction } from "../actions";
type ProfileValues = Record<string, unknown>;
export function ProfileForm({ profile, logoUrl }: { profile: ProfileValues; logoUrl: string | null }) {
  const [result, formAction] = useActionState(async (_: ActionResult | null, data: FormData) => updateMosqueProfileAction(data), null); const { showToast } = useToast(); const formRef = useRef<HTMLFormElement>(null); useEffect(() => { if (result) showToast(result.success ? "success" : "error", result.message); }, [result, showToast]); const value = (key: string) => String(profile[key] ?? "");
  return <form ref={formRef} action={formAction} className="space-y-6 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="grid gap-4 sm:grid-cols-2"><Field name="name" label="Nama Masjid" defaultValue={value("name")} required /><Field name="organizationName" label="Nama Yayasan / Organisasi" defaultValue={value("organizationName")} /><Field name="address" label="Alamat" defaultValue={value("address")} wide /><Field name="rt" label="RT" defaultValue={value("rt")} /><Field name="rw" label="RW" defaultValue={value("rw")} /><Field name="region" label="Wilayah" defaultValue={value("region")} /><Field name="contactNumber" label="Nomor Kontak" defaultValue={value("contactNumber")} /><Field name="chairmanName" label="Nama Ketua Takmir" defaultValue={value("chairmanName")} /><Field name="treasurerName" label="Nama Bendahara" defaultValue={value("treasurerName")} /><Field name="fiscalYear" label="Tahun Buku" type="number" defaultValue={value("fiscalYear")} required /></div><div className="rounded-2xl border border-green-200 bg-green-50 p-4"><h3 className="font-semibold text-green-950">Konfigurasi Iuran Default</h3><p className="mt-1 text-sm text-green-900">Dipakai saat tagihan belum tersedia.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="defaultContributionFee" label="Iuran Normal (Rp)" type="number" min="0" defaultValue={value("defaultContributionFee")} required /><Field name="specialContributionFee" label="Iuran Lansia / Disabilitas (Rp)" type="number" min="0" defaultValue={value("specialContributionFee")} required /></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 sm:col-span-2"><span className="text-sm font-medium text-slate-700">Logo Organisasi</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp" className="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm" /><span className="block text-xs text-slate-500">PNG, JPG, atau WEBP; maksimal 2 MB.</span>{logoUrl ? <Image src={logoUrl} alt="Logo organisasi saat ini" width={80} height={80} className="h-20 w-20 rounded-xl object-contain ring-1 ring-slate-200" /> : null}</label><label className="flex items-center gap-3 text-sm text-slate-700 sm:col-span-2"><input name="requireExpenseApproval" type="checkbox" value="true" defaultChecked={Boolean(profile.requireExpenseApproval)} className="h-4 w-4" /> Pengeluaran memerlukan verifikasi</label><label className="space-y-2 sm:col-span-2"><span className="text-sm font-medium text-slate-700">Teks Tanda Terima</span><textarea name="receiptText" defaultValue={value("receiptText")} rows={3} className="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm" /></label></div><button type="submit" className="rounded-xl bg-green-800 px-5 py-3 text-sm font-semibold text-white">Simpan Pengaturan</button></form>;
}
function Field({ name, label, defaultValue, type = "text", min, required, wide = false }: { name: string; label: string; defaultValue: string; type?: string; min?: string; required?: boolean; wide?: boolean }) { return <label className={`space-y-2 ${wide ? "sm:col-span-2" : ""}`}><span className="text-sm font-medium text-slate-700">{label}</span><input name={name} type={type} min={min} defaultValue={defaultValue} required={required} className="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm" /></label>; }
